@echo off
::Yes, its me. -ms
cls
Title Create Index
ECHO You can recursively map a folder [C:\Windows] or a drive [D:]
ECHO.
ECHO Network paths MUST be mapped to a letter first! (no \\server\)
ECHO.
set /p drive=Path to map files :
echo.
echo Generating File Listing ...
echo Please wait (under a minute)
set SAVEDATE=%DATE:/=-%
set SAVEDATE=%SAVEDATE: =%
set SAVEDATE=%SAVEDATE:Mon=%
set SAVEDATE=%SAVEDATE:Tue=%
set SAVEDATE=%SAVEDATE:Wed=%
set SAVEDATE=%SAVEDATE:Thu=%
set SAVEDATE=%SAVEDATE:Fri=%
set SAVEDATE=%SAVEDATE:Sat=%
set SAVEDATE=%SAVEDATE:Sun=%
::dir /b /s /A:D > Evidence_Listing_%SAVEDATE%.txt
dir /b /s %drive%:\ > %drive%.txt
echo. >> %drive%.txt
echo This file generated by: %username% >> %drive%.txt
echo %date% @ %time% >> %drive%.txt
echo Complete. Press any key to open listing.
pause
notepad %drive%.txt